### ISSUE TITLE
Fails to find libGraphCpp/graph.hpp

### ISSUE THREAD

**Issue by alalemp** [rFalque/embedded_deformation#1]
It has issue finding ./external_libraries/libGraphCpp/include/libGraphCpp/graph.hpp
I can see it find polyscope and all folders but not that one
-I/home/student/git/embedded_deformation/external_libraries/libGraphCpp/external_library/polyscope/src/../include
/home/student/git/embedded_deformation/include/embedded_deformation/embedDeform.hpp:17:10: fatal error: libGraphCpp/graph.hpp: No such file or directory
 #include "libGraphCpp/graph.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~
 
 I can't seem to find where it has target_include_directories for this?

**Comment by rFalque** [comment]
solved with 03d943f
