### ISSUE TITLE
bug when run in windows

### ISSUE THREAD

**Issue by lihongyi1234** [rFalque/embedded_deformation#4]
![image](https://github.com/rFalque/embedded_deformation/assets/36233282/245f59f6-18cb-4fce-bd2d-0fb454798e99)
![image](https://github.com/rFalque/embedded_deformation/assets/36233282/321c8048-f936-456a-b1c8-e2c973530d51)

i run your code in windows, i meet a bug using ceres to solve the defrom, do you meet this problem: on entry to ZHER   parameter number  0 had an illegal value. would you tell me your ceres version?

**Comment by rFalque** [comment]
Hi, I am using Ceres at version 1.14.0; however, I tried It on different installs and I have never seen anything remotely similar to the error you are reporting.

Did you run one of the samples provided in the data folder?

**Comment by lihongyi1234** [comment]
> Hi, I am using Ceres at version 1.14.0; however, I tried It on different installs and I have never seen anything remotely similar to the error you are reporting.
> 
> Did you run one of the samples provided in the data folder?

I solve thie problem by rewrite costFunction file and run success, I use ceres::NumericDiffCostFunction without jacobians

**Comment by rFalque** [comment]
Hi, I'm glad you managed to sort it out! I have tried autodiff in the past and I think it is faster (see doc [there](http://ceres-solver.org/automatic_derivatives.html)).

Feel free to fork the repo and publish that version if you want ;)

**Comment by lihongyi1234** [comment]
ok, I'll do it later




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rFalque/embedded_deformation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rFalque/embedded_deformation] bug when run in windows (Issue #4)





 
Hi, I'm glad you managed to sort it out! I have tried autodiff in the past and I think it is faster (see doc there).
 
Feel free to fork the repo and publish that version if you want ;)
